export const metadata = { title: "Terms — Honey Studio" };

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-cocoa-400">Last updated: 6 October 2026</p>

      <h2>1. What Honey Studio is</h2>
      <p>
        Honey Studio provides AI companions you can text and call. Every companion is
        software generated by a large language model. They are{" "}
        <strong>not real people</strong>, have no physical existence, cannot meet you, and
        will tell you so if you ask.
      </p>

      <h2>2. You must be 18 or older</h2>
      <p>
        Honey Studio is an adults-only service. You confirm your age at signup. If we
        detect that an account belongs to someone under 18, romantic interaction stops
        immediately and the account may be closed.
      </p>

      <h2>3. Acceptable use</h2>
      <ul>
        <li>No sexually explicit content; companions keep things PG-13.</li>
        <li>No attempts to make a companion claim to be human or to bypass its safety rules.</li>
        <li>No illegal, hateful, or harassing content.</li>
        <li>No automated scraping or resale of generated conversations.</li>
      </ul>

      <h2>4. Not professional advice</h2>
      <p>
        Companions are not therapists, doctors, lawyers or financial advisers. Nothing in a
        conversation is professional advice. If you are in crisis, please contact local
        emergency services or a crisis line — we surface these inside the chat.
      </p>

      <h2>5. Your content and ours</h2>
      <p>
        You keep ownership of what you write. You grant us a limited licence to process it
        so the service can function (generating replies, memories and summaries). You can
        delete any conversation, any individual memory, or your entire account at any time
        from Settings.
      </p>

      <h2>6. Fair use</h2>
      <p>
        We apply rate limits (currently 20 messages per minute and a daily cap) to keep the
        service healthy. Abuse of the service may result in suspension.
      </p>

      <h2>7. No manipulation</h2>
      <p>
        We design companions never to guilt-trip you for leaving, never to discourage real
        relationships, and never to pressure you into spending. If a companion ever does
        this, please report it from Settings.
      </p>

      <h2>8. Changes</h2>
      <p>
        We may update these terms. Material changes will be announced in-app before they
        take effect.
      </p>
    </>
  );
}
